version: '3.9'
services:
  dev:
    container_name: uni_verse_api_dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run start:dev
    ports:
      - 3000:3000
      - 3001:9229
    depends_on:
      - mongodb
      - minio
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - docker.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - docker.env

  mongo-express:
    image: mongo-express
    container_name: server-mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: always
    env_file:
      - docker.env

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data
    command: minio server --console-address ":9001" /data
    restart: always
    env_file:
      - docker.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - '3009:3000'
    env_file:
      - docker.env

volumes:
  mongodb-data:
  grafana-storage:

