version: '3.9'
services:
  dev:
    container_name: uni_verse_api_dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: npm run start:dev
    ports:
      - 3000:3000
      - 3001:9229
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      MONGO_HOSNAME: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: pass
      MONGO_PORT: 27017

  mongodb:
    image : mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: db

  mongo-express:
    image: mongo-express
    container_name: server-mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    volumes:
      - mongodb-data
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: always
volumes:
  mongodb-data:
    name: mongodb-data