### DEV ###
FROM node:22
# Safer workdir
WORKDIR /usr/src/app
# Copy package.json and package-lock.json
COPY ./package*.json ./

RUN npm ci
# Copy source code
COPY . .

CMD ["npm", "run", "test:watch"]

