apiVersion: v1
kind: ConfigMap
metadata:
  name: uni-verse-conf
data:
  ME_CONFIG_MONGODB_SERVER: uni-verse-database-service
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  ME_CONFIG_BASICAUTH_USERNAME: root
  ME_CONFIG_BASICAUTH_PASSWORD: pass
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: pass
  MONGO_INITDB_DATABASE: db
  MONGO_HOSTNAME: uni-verse-database-service
  MONGO_USERNAME: root
  MONGO_PASSWORD: pass
  MONGO_PORT: "27017"
  MONGO_DATABASE: uniVerse
  JWT_SECRET: uniVerseJwtSecret
  JWT_EXPIRATION_TIME: 60s
  JWT_ACCESS_TOKEN_SECRET: uniVerseJwtSecret
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: 60s
  JWT_REFRESH_TOKEN_SECRET:  uniVerseJwtSecret
  JWT_REFRESH_TOKEN_EXPIRATION_TIME:  24h
  MINIO_ROOT: miniokey
  MINIO_ROOT_USER: root
  MINIO_ROOT_PASSWORD: miniosecret
  MINIO_ENDPOINT: minio.minio.svc.cluster.local
  MINIO_PORT: "9000"
  STRIPE_SECRET_KEY: lol
  STRIPE_CURRENCY: usd
  FRONTEND_URL: https://uni-verse.vagahbond.com
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: pass
  UNIVERSE_DONATION_PRODUCT_ID: lol
  ELASTICSEARCH_NODE: http://elasticsearch-1654937620:9200
  ELASTICSEARCH_USERNAME: elastic
  ELASTICSEARCH_PASSWORD: admin
  STRIPE_PUBLISHABLE_KEY: lol
  NEXT_PUBLIC_API_URL: https://uni-verse.api.vagahbond.com
  GOOGLE_AUTH_CLIENT_ID: lol
  GOOGLE_AUTH_CLIENT_SECRET: lol
  SPOTIFY_AUTH_CLIENT_ID: lol
  SPOTIFY_AUTH_CLIENT_SECRET: lol
  NEXTAUTH_URL: https://uni-verse.vagahbond.com
  NEXTAUTH_SECRET: secret
  NEXT_PUBLIC_MAX_FILE_SIZE: "10000000"
  NEXT_PUBLIC_MAX_IMAGE_SIZE: "3000000"
