apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: uni-verse-api
    app:  uni-verse-api
  name: uni-verse-api-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}